# 여기부터 CNN모델 

In [112]:
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint
from keras.layers.normalization import BatchNormalization
import numpy as np

# Initialising the CNN
# classifier = Sequential()
model = Sequential()

# Step 1 - Convolution
# classifier.add(Conv2D(16, (3, 3), padding='same', activation='relu', input_shape=(224, 224, 3)))
# classifier.add(Conv2D(16, (3, 3), activation='relu'))
# classifier.add(MaxPooling2D(pool_size=(2, 2)))
# classifier.add(Dropout(0.25))

# classifier.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
# classifier.add(Conv2D(64, (3, 3), activation='relu'))
# classifier.add(MaxPooling2D(pool_size=(2, 2)))
# classifier.add(Dropout(0.25))

# classifier.add(Conv2D(32, (3, 3), padding='same', activation='relu'))
# classifier.add(Conv2D(32, (3, 3), activation='relu'))
# classifier.add(MaxPooling2D(pool_size=(2, 2)))
# classifier.add(Dropout(0.25))

# classifier.add(Flatten())
# classifier.add(Dense(512, activation='relu'))
# classifier.add(Dropout(0.5))
# classifier.add(Dense(5, activation='softmax'))

model.add(Conv2D(16, (4, 4), padding='same', use_bias=False, input_shape=(64, 64, 3)))   # 사진 사이즈 조정
model.add(BatchNormalization(axis=3, scale=False))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(4, 4), strides=(4, 4), padding='same'))
model.add(Dropout(0.3))        # 앙상블 효과 

model.add(Conv2D(32, (4, 4), padding='same', use_bias=False))
model.add(BatchNormalization(axis=3, scale=False))
model.add(Activation("relu"))
#model.add(Flatten())
model.add(MaxPooling2D(pool_size=(4, 4), strides=(4, 4), padding='same'))
model.add(Dropout(0.3))

#model.add(Conv2D(64, (4, 4), padding='same', use_bias=False))
#model.add(BatchNormalization(axis=3, scale=False))
#model.add(Activation("relu"))
#model.add(Flatten())
#model.add(MaxPooling2D(pool_size=(4, 4), strides=(4, 4), padding='same'))
#model.add(Dropout(0.3))

#model.add(Conv2D(128, (3, 3), padding='same', use_bias=False))
#model.add(BatchNormalization(axis=3, scale=False))
#model.add(Activation("relu"))
model.add(Flatten())
#model.add(Dropout(0.25))
model.add(Dense(512, activation='relu'))
#model.add(Dropout(0.25))
model.add(Dense(4, activation='softmax'))     # 판단할 카테고리 수  9
model.summary()

# Compiling the CNN
model.compile(optimizer='adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])





_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_50 (Conv2D)           (None, 64, 64, 16)        768       
_________________________________________________________________
batch_normalization_50 (Batc (None, 64, 64, 16)        48        
_________________________________________________________________
activation_50 (Activation)   (None, 64, 64, 16)        0         
_________________________________________________________________
max_pooling2d_50 (MaxPooling (None, 16, 16, 16)        0         
_________________________________________________________________
dropout_50 (Dropout)         (None, 16, 16, 16)        0         
_________________________________________________________________
conv2d_51 (Conv2D)           (None, 16, 16, 32)        8192      
_________________________________________________________________
batch_normalization_51 (Batc (None, 16, 16, 32)        96        
__________

In [113]:
# Part 2 - Fitting the CNN to the images
from keras.preprocessing.image import ImageDataGenerator

# train_datagen = ImageDataGenerator(rescale = 1./255)

# 데이터셋 불러오기
train_datagen = ImageDataGenerator(rescale=1./255)   #스케일링을 줄여주는것 (normalization 적용해보면 더 좋아질 수 있음) 
                                   #width_shift_range=0.2,
                                   #height_shift_range=0.2)
                                   #validation_split=0.33)
                                   #otation_range=10,
                                   #width_shift_range=0.2,
                                   #height_shift_range=0.2,
                                   #shear_range=0.2)
                                   #zoom_range=[0.9, 2.2],
                                   #horizontal_flip=True,
                                   #vertical_flip=True,
                                   #fill_mode='nearest')
                                   #validation_split=0.33)

#test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory('/home/shy9546/Downloads/color/train',   # 훈련시킬 사진 경로
                                                 shuffle=True,
                                                 seed=13,
                                                 target_size = (64, 64),    # 사이즈 지정해주기
                                                 batch_size = 15,
                                                 #color_mode='grayscale',
                                                 color_mode='rgb',
                                                 class_mode = 'categorical')
                                                 #subset="training")
validation_set = train_datagen.flow_from_directory('/home/shy9546/Downloads/color/valid',
                                                 shuffle=True,
                                                 seed=13,
                                                 target_size = (64, 64),
                                                 batch_size = 10,
                                                 #color_mode='grayscale',
                                                 color_mode='rgb',
                                                 class_mode = 'categorical')
                                                 #subset="validation")


Found 317 images belonging to 4 classes.
Found 80 images belonging to 4 classes.


# 다시 원래 코드

In [114]:
from keras.callbacks import CSVLogger

csv_logger = CSVLogger('./log.csv', append=True, separator=';')

##hist = model.fit_generator(training_set,
#                         epochs = 50,   # 반복수 변경가능
#                         validation_data = validation_set
#                         )
STEP_SIZE_TRAIN = training_set.n
STEP_SIZE_VALID = validation_set.n
model.fit_generator(generator = training_set,
                    #steps_per_epoch=STEP_SIZE_TRAIN,
                   validation_data=validation_set,
                    #validation_steps=STEP_SIZE_VALID,
                   epochs=15)
from keras.models import load_model

model.save('cnn_attraction_keras_model_color5.h5')

# output = classifier.predict_generator(test_set, steps=5)
# print(test_set.class_indices)
# print(output)



Epoch 1/15
22/22 [==============================] - 8s 362ms/step - loss: 1.3012 - acc: 0.6594 - val_loss: 0.1227 - val_acc: 0.9750
Epoch 2/15
22/22 [==============================] - 4s 165ms/step - loss: 0.2588 - acc: 0.9144 - val_loss: 0.0710 - val_acc: 0.9875
Epoch 3/15
22/22 [==============================] - 4s 172ms/step - loss: 0.1900 - acc: 0.9265 - val_loss: 0.2359 - val_acc: 0.9125
Epoch 4/15
22/22 [==============================] - 4s 164ms/step - loss: 0.0914 - acc: 0.9666 - val_loss: 0.4810 - val_acc: 0.7875
Epoch 5/15
22/22 [==============================] - 4s 170ms/step - loss: 0.0848 - acc: 0.9879 - val_loss: 0.0237 - val_acc: 1.0000
Epoch 6/15
22/22 [==============================] - 3s 156ms/step - loss: 0.0211 - acc: 0.9939 - val_loss: 0.0135 - val_acc: 1.0000
Epoch 7/15
22/22 [==============================] - 4s 164ms/step - loss: 0.0603 - acc: 0.9909 - val_loss: 0.0850 - val_acc: 0.9625
Epoch 8/15
22/22 [==============================] - 3s 157ms/step - loss: 0.

In [115]:
from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale=1./255)
prediction_set = train_datagen.flow_from_directory('/home/shy9546/Downloads/color_temp/test1',
                                                  target_size=(64,64),
                                                  #color_mode='grayscale',
                                                  color_mode='rgb',
                                                  batch_size=1,
                                                  class_mode =None,
                                                  shuffle=False,
                                                  seed=13)

Found 8 images belonging to 1 classes.


In [117]:
from keras.models import load_model


#model.load('./cnn_attraction_keras_model11.h5')
#model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

model = load_model('./cnn_attraction_keras_model_color5.h5')
# 모델 평가하기
print("-- Evaluate --")

scores = model.evaluate_generator(
            validation_set)
            #steps = 10)

print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

# 모델 예측하기
print("-- Predict --")
STEP_SIZE_TEST = prediction_set.n
prediction_set.reset()

output = model.predict_generator(
            prediction_set,
            verbose=1)

predicted_class_indices = np.argmax(output,axis=1)
labels = (training_set.class_indices)
labels = dict((v,k) for k,v in labels.items())
predictions = [labels[k] for k in predicted_class_indices]


print(output)
print(predictions)
print(prediction_set.filenames)


-- Evaluate --
acc: 100.00%
-- Predict --
8/8 [==============================] - 2s 210ms/step
[[7.6740885e-01 1.0530032e-03 8.1495394e-04 2.3072331e-01]
 [5.8564398e-04 8.0859888e-01 2.4043653e-02 1.6677178e-01]
 [8.2993170e-04 2.3666643e-01 7.6244467e-01 5.8969763e-05]
 [1.7586246e-03 4.1207038e-03 2.7640423e-04 9.9384427e-01]
 [1.1529122e-02 1.3321157e-02 2.1457756e-03 9.7300398e-01]
 [4.2368183e-06 2.3291336e-01 3.9935482e-04 7.6668304e-01]
 [2.0348493e-04 8.7782103e-01 1.2106070e-01 9.1471040e-04]
 [2.5220418e-06 2.1930570e-03 2.8693341e-06 9.9780148e-01]]
['blue', 'orange', 'red', 'white', 'white', 'white', 'orange', 'white']
['test_data/1.jpg', 'test_data/2.jpg', 'test_data/3.jpg', 'test_data/4.jpg', 'test_data/5.jpg', 'test_data/6.jpg', 'test_data/7.jpg', 'test_data/8.jpg']
